### ISSUE TITLE
Visual issues on Win 10

### ISSUE THREAD

**Issue by dkast** [Yummygum/city-lights-ui-atom#1]
Hi! First of all, congrats on an awesome looking theme! 😎

I found some visual bugs on Atom on Win 10, where the UI font and the scrollbars are not being themed correctly, I assume there's no actual support on Windows?

![image](https://user-images.githubusercontent.com/3997998/32397433-d1cd12b0-c0b7-11e7-90f6-f468f6c301f0.png)

I hope there is proper support on Windows soon because this is the first theme that actually makes me want to change the default One Dark.

Thanks!

**Comment by jeffmartinxyz** [comment]
Same issue for me.

**Comment by noudadrichem** [comment]
Hi @dkast & @jeffmartinxyz,

I patched a new update to the repo, can you guys try to update and let me know if the fonts are oke?

Sincerely

**Comment by dkast** [comment]
Hi @noudadrichem, I can confirm that the fonts are displaying correctly on Win 10 👍

Thanks!
