### ISSUE TITLE
Adaptive color scheme

### ISSUE THREAD

**Issue by YurySolovyov** [Yummygum/city-lights-ui-atom#14]
Themes like [one-dark-ui](https://atom.io/themes/one-dark-ui) are able to adapt to selected syntax theme (see FAQ section at the bottom) to look more natural when users use non-matching UI+Syntax themes. (e.g. city-lights-ui + solarized-dark)

I think it would ease the adoption of this theme and makes sense in general.

**Comment by noudadrichem** [comment]
Hi @YurySolovyov ,

@Yummygum we decided to not make the whole UI adaptive. We do are looking at some elements that could be adaptive to satisfy your needs.

Sincerely

**Comment by YurySolovyov** [comment]
Sure, I only mean reasonably adaptive, so I don't have places like:
![image](https://user-images.githubusercontent.com/2168518/33208097-49ce5976-d121-11e7-9df2-3a46e66436b9.png)
Which I think should fit better.

**Comment by noudadrichem** [comment]
Totally right! @YurySolovyov
