### ISSUE TITLE
.rspec icon is cut off

### ISSUE THREAD

**Issue by joshmosh** [Yummygum/city-lights-ui-atom#15]
If this is not the correct project to file this issue please let me know. The rspec icon in the sidebar is cutoff. Attached is a screenshot.

This seems to happen in both Atom v1.22.0 and Atom Beta v1.23.0-beta0 running city-lights-ui v1.1.6. Let me know if you need anymore information.

Thanks!

<img width="310" alt="atom-city-lights-ui-rspec-cutoff" src="https://user-images.githubusercontent.com/34509/32734918-f9263186-c858-11e7-8c59-f205a6301b7e.png">

**Comment by joshmosh** [comment]
Closing this. This is related to the file-icons package.

**Comment by noudadrichem** [comment]
Hi @joshmosh,

Thanks for reporting this bug, It does indeed belong in the 'icon package' repo.

Sincerely
