### ISSUE TITLE
missing URI Handling icon (settings panel)... 

### ISSUE THREAD

**Issue by tyrollins** [Yummygum/city-lights-ui-atom#21]
Great work! Just noticed however, in Atom Beta 1.23 there is a new tab in the settings panel for URI Handling and it seems to be missing its icon...

<img width="969" alt="icon" src="https://user-images.githubusercontent.com/4915845/33242783-f4aa3fea-d28e-11e7-8356-adf340c7b137.png">

**Comment by noudadrichem** [comment]
Hi @tyrollins,

As you said it's a new tab. We'll cover this asap.
Thank you for addressing the issue!

Sincerely
