### ISSUE TITLE
Folder icon color change

### ISSUE THREAD

**Issue by claudiozoocial** [Yummygum/city-lights-ui-atom#22]
Hi, first of all i love the theme, syntax and icons, really nice work guys!. The only issue for me it's when i change a file inside a folder the folder icon color doesn't change, and it's a little difficult to know where i changed a file, that's all thanks :D

**Comment by noudadrichem** [comment]
Hi @claudiozoocial,

I included this in the next update of the theme.

**Comment by claudiozoocial** [comment]
@noudadrichem thanks!!! 👍
