### ISSUE TITLE
Find/Replace font color is hard to read

### ISSUE THREAD

**Issue by nwinkler** [Yummygum/city-lights-ui-atom#23]
Let me start with saying that I really love the City Lights theme so far! Thanks for the great work!

One thing that bothers me is that I find the font color in the "Find" box hard to read:
![image](https://user-images.githubusercontent.com/907063/33931250-bf8ed37a-dfef-11e7-893f-5a4d88d95e9f.png)

It looks like it's a different color from e.g. the "New File" dialog, or the fuzzy finder.

Would it be possible to make the font color in the Find/Replace input fields a bit brighter so it's easier to read them?

I don't have any custom style settings, other than using "Source Code Pro for Powerline" as the editor font, with size 14. While checking that, I found that the font color in the settings is also a bit too unobtrusive, e.g. in the "Font Family" field, it's hard to see a difference to the fields that have the default value:

![image](https://user-images.githubusercontent.com/907063/33931446-4d1b8918-dff0-11e7-8429-3c9c92cb7e69.png)

**Comment by noudadrichem** [comment]
Hi @nwinkler,

I'll take a look at this!
Thanks for making an issue.

Sincerely

**Comment by noudadrichem** [comment]
Fix will be released in the next update.

**Comment by nwinkler** [comment]
Awesome - thanks for the quick response!
