### ISSUE TITLE
city-lights-ui hides needed tab-bar for Remote FTP to work

### ISSUE THREAD

**Issue by jprusik** [Yummygum/city-lights-ui-atom#24]
Not sure where the responsibility to fix this lies, but it might be worth looking at not hiding the tabs above the tree-view panel (where the "Projects" tab appears). If it is hidden, remote ftp will not display its panel (since you can't switch to it with city lights hiding the relevant tab-bar)

more details from the remote-ftp issue tracker:
https://github.com/icetee/remote-ftp/issues/1081#issuecomment-351543308

**Comment by cbwiedel** [comment]
+1 Also having this issue.

**Comment by noudadrichem** [comment]
The tab bar in the tree-view in my opinion is still a waste of space. I didn't knew the use case until now. I'll make a config that shows/hides the tab bar in the tree view.

Sincerely

**Comment by noudadrichem** [comment]
Hi @jprusik, @cbwiedel & @icetee,

In the next update the city-lights-ui theme will have a settings panel where you can choose between showing & hiding the tab bar in the tree-view.

Sincerely

**Comment by noudadrichem** [comment]
![image](https://user-images.githubusercontent.com/16288476/34292502-77f2bdd8-e701-11e7-889c-c12a0fd38e59.png)
You can now find this option in the settings panel of the city-lights-ui theme.
