### ISSUE TITLE
No has icon for URI Handling

### ISSUE THREAD

**Issue by icetee** [Yummygum/city-lights-ui-atom#26]
In the new Atom version added new menu option.

<img width="850" alt="screenshot 2017-12-14 01 57 00" src="https://user-images.githubusercontent.com/1855340/33970228-2ea8f4de-e072-11e7-8690-43c71ee73f97.png">

**Comment by noudadrichem** [comment]
Hi @icetee,

This will be fixed in the next update, thank you for pointing it out.
