### ISSUE TITLE
Wrong indentation on files in file tree?

### ISSUE THREAD

**Issue by pederjohnsen** [Yummygum/city-lights-ui-atom#27]
My file tree doesn't look like in the provided screenshots in this repo, for me all files get the same indentation no matter where in the folder structure they live:
![https://i.imgur.com/6u7nN6V.png?1](https://i.imgur.com/6u7nN6V.png?1)

`common.coffee` lives under `test/src` and `index.html` under `test`, but `mocha-3.2.0.css` lives under `test/vendor/styles`, but like this it's near impossible to be sure it's not just in the same folder as `index.html`

**Comment by pederjohnsen** [comment]
Sorry, seems to be OK in latest beta release.. (I thought I had the latest but turns out I never)

**Comment by noudadrichem** [comment]
Hi  @pederjohnsen,

Not sure what OS you're using, but seems you already fixed it.
Stil thanks for making out an issue of this, we appriciate the suppor!

Sincerely
