### ISSUE TITLE
file-icons in tabs doesn't work with city-lights ui

### ISSUE THREAD

**Issue by icp1994** [Yummygum/city-lights-ui-atom#28]
![city-lights](https://user-images.githubusercontent.com/15713555/34352307-c7e9cdec-ea47-11e7-8358-1cbdc695a488.png)
![one-dark](https://user-images.githubusercontent.com/15713555/34352308-c9df2e30-ea47-11e7-934b-32b29ba29a19.png)

I tested with seti icons and city-lights-icons too. They work but seti icons looks out of place in tabs

**Comment by noudadrichem** [comment]
Hi @icp1994,

Sorry for the late response, I'll take a look at this. 😊

Sincerely
