### ISSUE TITLE
styleguide shows a black screen

### ISSUE THREAD

**Issue by jhessin** [Yummygum/city-lights-ui-atom#30]
If you load the styleguide (default ctrl-shift-g) with this theme active the entire ui goes black. The only way to fix it is to switch tabs (ctrl-tab) or close the window (ctrl-w). Not a big deal but may be indicative of a larger issue.

**Comment by noudadrichem** [comment]
Mmm, this indeed is very weird. It doesn't show any errors. So it shouldn't be a big issue.

**Comment by olliefr** [comment]
Can confirm that it still happens with everything latest as of today (( I was slowly writing up a config for my toolbar and was going to look up what icons are available in Octicons, following [Hacking Atom](https://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/#atom-styleguide) guide. Please consider reopening the issue and fixing, it would be good to have this working. I can ctrl-tab out of the *Styleguide*, or ctrl-w to close it, but there is no way I can see it.
