### ISSUE TITLE
Project Title Highlight

### ISSUE THREAD

**Issue by Nchudson95** [Yummygum/city-lights-ui-atom#37]
The portion of the tree-view with the project name has a background similar to that of the active tab among your open code files. When I restart Atom and set the UI to City-Lights, this doesn't happen. But, the moment I close Atom and reopen a project, this weird UI glitch shows up.

**Comment by noudadrichem** [comment]
Hi,

Thanks for reporting a bug! Do you mind making a GIF/screencapture on what happends. I'm not sure I understand. 

I do know that in the UI theme settings we made a toggle to show/hide the tab bar in the tree view. You could try that.

Sincerely

**Comment by Nchudson95** [comment]
Sure! Here is an screenshot of what I'm talking about. There is a "Project" tab that is highlighted that shows up for some reason. When I change the Title Bar setting under the Core portion of settings, Atom will restart and that tab effect on "Project" will not appear. It shows up once I close Atom and reopen a project.
![screen shot 2018-04-02 at 1 25 06 pm](https://user-images.githubusercontent.com/5210444/38206742-88e72a44-3679-11e8-8b1c-e9d9432fa9e4.png)

**Comment by noudadrichem** [comment]
Mmm. And if you instead of restart Atom Just reload it? The effect of the checkbox should be immidiatly visible

**Comment by Nchudson95** [comment]
It's not working for me. I didn't have that checkbox checked before when this issue was showing up. I checked it, restarted Atom, the issue persisted. Then I unchecked it, restarted Atom, the issue disappeared. But, then when I reopen a project without doing anything in Settings, the issue shows up again.

**Comment by noudadrichem** [comment]
Only thing I can come up with is reinstalling and/or updating Atom itself.
Closing it for now.
