### ISSUE TITLE
UI Theme issue

### ISSUE THREAD

**Issue by yanniznik** [Yummygum/city-lights-ui-atom#4]
Beautiful theme, thanks for your contribution.

Whenever switching to CityLights UI, the fonts becomes all messed up. The syntax theme works correctly. All fonts are set to default.
![weird](https://user-images.githubusercontent.com/9571261/32413029-c6be727c-c208-11e7-8a78-e8d7ee36b9d5.png)

Atom 1.21.2 @ Ubuntu 16.04

**Comment by six7** [comment]
Had the same problem, coincidentally afterwards installed the "fonts" package and the UI font is now found.

**Comment by yanniznik** [comment]
By the "fonts" package, do you mean Syntax package?

**Comment by six7** [comment]
This one: https://atom.io/packages/fonts

City Lights seems to use a font that's not found on default systems, but is included in above package.

**Comment by noudadrichem** [comment]
@yanniznik I'll check this out! Did you downloaded the last patch? I changed some other font issues.
