### ISSUE TITLE
Configurable padding for file tree view

### ISSUE THREAD

**Issue by slnt** [Yummygum/city-lights-ui-atom#47]
I find that the directories and such in the tree view are a tad too closer together for me. 

It would be nice if there was an configurable setting to increase the number of px between each element in the tree view.

**Comment by noudadrichem** [comment]
Hi @slnt ,

This is indeed a good idea! 

Maybe something to mention. In the last updated version you're able to change the font sizes of the tree view/tabs in the theme settings under `settings > Themes > City Lights UI > Settings`. Maybe that helps with your visibility problem for now.

**Comment by slnt** [comment]
Another thing perhaps would be a configurable font! I'd love to match the UI font with my editor font.

**Comment by noudadrichem** [comment]
The font we're using on OSX is by design. We'll consider this. What platform are you running The theme on?

**Comment by slnt** [comment]
macOS 10.13.6

**Comment by noudadrichem** [comment]
The SF font is used by design. We'll take this option in consideration. 😊
