### ISSUE TITLE
.s icon missing

### ISSUE THREAD

**Issue by fabulousduck** [Yummygum/city-lights-ui-atom#8]
When using ASM files, atom will default the icon to the default atom icon because there is none in the icon pack

**Comment by noudadrichem** [comment]
Can you supply us with a preview link of the logo/icon you like to see and the extensions that are available?

**Comment by noudadrichem** [comment]
Hi @fabulousduck 

This issue should be placed in https://github.com/Yummygum/city-lights-icons-atom/issues.
I close it
