### ISSUE TITLE
[Request] Terminal theme

### ISSUE THREAD

**Issue by tbnv** [Yummygum/city-lights-ui-atom#9]
Hi guys!

Can be closed and kept just a reminder for a feature request, following the short talk we had on Twitter.

A **Terminal theme** to match City Lights would be very awesome. I often have Atom and Terminal open at the same time and I like them to have the same colors. 🙂

Not urgent btw.

**Comment by noudadrichem** [comment]
Hi @tbnv,

We have this on our radar. Do you use a 3rd party terminal application?

Sincerely

**Comment by tbnv** [comment]
Hi,

Thanks. I’m using the default Terminal.app — I wanted to use Hyper.is but it’s not stable enough and I don’t need the advanced features from iTerm.

**Comment by ashtonlance** [comment]
Any updates on this? I'd love to have this theme in ITerm

**Comment by noudadrichem** [comment]
Hi @ashtonlance,

If you shoot me an email on noud@yummygum.com I can send you a contributor made City Lights .itermcolors file. This counts for any of you guys. I'm personally using this hyper configuration:

```
    fontSize: 12,
    fontFamily: 'Droid Sans Mono',
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorShape: 'BEAM',
    foregroundColor: '#b7c5d3',
    backgroundColor: '#181e24',
    padding: '0px 16px 8px 16px',
    colors: {
      black: '#333f4a',
      red: '#d95468',
      green: '#8bd49c',
      yellow: '#ebbf83',
      blue: '#539afc',
      magenta: '#b62d65',
      cyan: '#70e1e8',
      white: '#718ca1',
      lightBlack: '#41505e',
      lightRed: '#d95468',
      lightGreen: '#8bd49c',
      lightYellow: '#f7dab3',
      lightBlue: '#5ec4ff',
      lightMagenta: '#b62d65',
      lightCyan: '#70e1e8',
      lightWhite: '#b7c5d3'
    },
```
Which includes all the city lights colors.

**Comment by thomaskrag** [comment]
@noudadrichem any chance you could publish an npm of this and list it on https://github.com/bnb/awesome-hyper?

Thanks a lot for the theme though. Looks great! <3

**Comment by licatajustin** [comment]
@tbnv, [here](https://gist.github.com/licatajustin/dbfe189a202c58a0aedce6bc944ca99c) is a quick 5-minute creation of a Terminal version. Definitely not perfect, but it's a working start. Definitely open to changes by anyone, including the City Lights author 😊

**Comment by tbnv** [comment]
@licatajustin Haha, cool thanks! 🙂

**Comment by tbnv** [comment]
@licatajustin I forked it and made some small changes. Anyway, thanks for having started with this. 👍

**Comment by noudadrichem** [comment]
Great addition @licatajustin, thanks! It's definitely a team effort of @Yummygum

**Comment by ruimarinho** [comment]
Here's my take: https://github.com/ruimarinho/iterm2-city-lights

**Comment by noudadrichem** [comment]
Looks nice!

**Comment by daenuprobst** [comment]
The following json snippet can be directly used as a theme in windows terminal. The colours are taken from the terminal settings in the vs code theme. Bright colours have been added by increasing the lightness/value of the original colours.

https://gist.github.com/daenuprobst/ebdc3644ae41cb76e5e5a2a24f097855
